### PR TITLE
Drop support for `i18n/Index` which has been unsupported for more than 10 years

### PR DESCRIPTION
**Pull request by chutzimir**
The translation "Index" is documented at
https://wiki.debian.org/DebianRepository/Format#A.22Translation.22_indices

	The directory dists/$DIST/$COMP/i18n/ contains the file index,
	with a SHA1 field listing the description indices in that
	directory

Funny enough, the Debian mirrors do not host an `i18n/Index` file. E.g.,
there is no http://ftp.debian.org/debian/dists/stable/main/i18n/Index,
but the files in the directory are indexed in
http://ftp.debian.org/debian/dists/stable/InRelease instead.

Ubuntu mirrors do host the i18n/Index, but the files under i18n are
also indexed in the Release file.

Since we find the translation files while parsing the Release, there is
no need to look into a separate index for them. This index does not have
the by-hash checksums so it is not very useful anyway.

### CODE REVIEW

**Comment by chutzimir** [comment]
I found some background official stance about the status of `i18n/Index` so force-pushed to the branch to reflect the new explanation. This one makes much more sense now:

This is a follow up of Debian bug #649314

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=649314

To also quote https://github.com/Debian/apt/commit/8e3900d0d7efc11d538b944ed1d9e4e3d5286ff6 (from 2012)

```
i18n/Index was never used outside debian - and even here it isn't used
consistently as only 'main' has such a file. As the Release file now
includes the Translation-* files we therefore drop support for
i18n/Index.

A version supporting it was never part of a debian release and still
supporting it would mean that we get 99% of the time a 404 as response
to the request anyway and confuse archive maintainers who want to
provide all files APT tries to acquire.
```

**Comment by chutzimir** [comment]
Support for `i18n/Index` was introduced in apt 0.8.1 (released on September 4, 2010), and dropped in apt 0.9.0 (released on April 17, 2012). It's been ten years since this files has not been officially supported, so let's drop support for it.

**Comment by chutzimir** [comment]
@jbouse May I have your attention to this PR please? I made an effort to split up the changes into small PRs so they are very easy to review. As explained in the latest commit message, and in the apt source code itself, support for i18n/Index was never really used anywhere so it is safe to remove.

**Comment by SupaHiro** [comment]
@chutzimir  did this change end up in #156 or did we leave it out? I want to double check if this still needs to be reviewed.

**Comment by chutzimir** [comment]
> @chutzimir did this change end up in #156 or did we leave it out? I want to double check if this still needs to be reviewed.

I can confirm it is in #156.

**Pull request closed without merging**
