### PR TITLE
Simple PR that merged most of all PR and couple of Issues

### LINKED ISSUE #19: sanitise_url is not correctly picking up specified ports
The regex is incorrect:

Change:     $uri =~ s&:\d+/&/&;    # and port information
To:     $uri =~ s&:\d+/$&/&;    # and port information

### LINKED ISSUE #130: bz2 or xz or gz (buster-backports i18n xz)
https://github.com/apt-mirror/apt-mirror/blob/7d521b168ab34fd38fd38bbb26acad1f43e262a7/apt-mirror#L523
                    if ( $filename =~ m{^$component/i18n/Translation-[^./]*\.(bz2||xz||gz)$} )

### LINKED ISSUE #146: Set a different user agent to avoid 403 Unauthorized
Hi,

Some providers like CloudFlare forbid `wget`.

Would it be possible to add a user-agent to change default wget/1.3.X  ?
https://github.com/apt-mirror/apt-mirror/blob/7d521b168ab34fd38fd38bbb26acad1f43e262a7/apt-mirror#L266

Something like this :
`exec 'wget', '-U', '<ADifferentUserAgent>', '--no-cache', '--limit-rate=' . get_variable("limit_rate"), '-t', '5', '-r', '-N', '-l', 'inf', '-o', get_variable("var_path") . "/$stage-log.$i", '-i', get_variable("var_path") . "/$stage-urls.$i", @args; `

I shall do PR, but is it usefull or am I missing something ?

### PR DESCRIPTION
**Pull request by steamboatid**
- Some new features added :
	- new config option "use_proxy"  (PR #48)
	- new config option "http_proxy"  (PR #48)
	- new config option "proxy_user"  (PR #48)
	- new config option "proxy_password"  (PR #48)
	- new config option "user_agent"  (fixes #146)
	- new config option "timeout"
		previously hard-coded, now the setup will affect on read, dns and connect timeout
	- new config option "tries"
		previously hard-coded
	- new config option "cookies_file"
		some server provide cookies, so we should provide cookies to legitimate cookie-full servers
	- new config option "dry_run" (PR #86)
	- new config option "max_redirect"
		reducing redirect attempt, to fasten Wget
	- new config option "ip_v6"
		some network problematic with ipv6
	- merge pull request (PR) #36, #40, #48, #77, #86, #95, #96, #100, #103, #105, #111, #112, #115, #116, #120, #127, #131, #136, #143
	- bz2 or xz or gz (buster-backports i18n xz) (fixes #130)
	- port number (fixes #19)

### CODE REVIEW

**Comment by jbouse** [comment]
I haven't been able to do a functional test but looking over this PR it looks good. If someone else has verified it's functional I can go ahead and get it merged and we can close all related PRs/issues that it addresses.

**Comment by steamboatid** [comment]
> I haven't been able to do a functional test but looking over this PR it looks good. If someone else has verified it's functional I can go ahead and get it merged and we can close all related PRs/issues that it addresses.

Hi @jbouse,

acttually, I already plenty of new feature at my fork. 
please take a look at it.

thanks.

**Comment by Kepler-Br** [comment]
Not working anymore for some reason
Using prepackaged mirror.list, but it's always says that "0 bytes will be downloaded into archive" with dry run
I'm using debian buster in docker container, but in host ubuntu I have the same issue
premirror.sh is from your repo
Here's my log:
```
Running the Pre Mirror script ...                                                                                           
(/UbuntuMirror/New/var/premirror.sh)                                                                                         
                                                                                                                             
                                                                                                                             
 Pre Mirror script has completed. See above output for any possible errors.                                                  
                                                                                                                             
                                                                                                                             
                                                                                                                             
 Prepare indexes files: []                                                                                                   
   Downloading 335 index files using 2 threads...                                                                            
cat: /UbuntuMirror/New/var/index-log.0: No such file or directory                                                            
=cat: /UbuntuMirror/New/var/index-log.1: No such file or directory                                                           
=  current 404 Fails: 0                                                                                                      
                                                                                                                             
    Checksum Checking: Packages* files.. 
   Preparing Packages* files checksum: [] {0 lines}. 
   [Packages* Files] Checksum Type:    MD5      --- checksum file NOT exists
   [Packages* Files] Checksum Type:   SHA1      --- checksum file NOT exists
   [Packages* Files] Checksum Type: SHA256      --- checksum file NOT exists


 Processing translation indexes: [TTTTT]

 Processing DEP-11 indexes: [DDDDD]

 Processing SHA256 by-hash files [HHHHH]

 Processing cnf indexes: [CCCCC]

 Processing debian-installer: [EEEEE]

 Processing debian-iso files: [IIIIII]

 Processing indexes: {S=source, B=Binary} [SS  BBBBB]

 No file with mismatch size found. 


 Checksum Checking: Pre-Mirroring 
   [Pre Mirroring] Checksum Type:    MD5        --- checksum file NOT exists
   [Pre Mirroring] Checksum Type:   SHA1        --- checksum file NOT exists
   [Pre Mirroring] Checksum Type: SHA256        --- checksum file NOT exists



 Main download.. 

 0 bytes will be downloaded into archive [0 urls].
 A dry-run was requested, no download performed, exiting.
```

**Comment by frmjar** [comment]
Anyone can merge this epic PR?

**Comment by jbouse** [comment]
> Anyone can merge this epic PR?

Honestly this PR is exactly that... EPIC. Far too much to simply evaluate and unpack before merging.

**Comment by chutzimir** [comment]
This doesn't look like a merge request prepared for merge into the official repository - the README.md is actually getting updated with the text `steamboatid's fork of apt-mirror`.

Please consider reviewing #154 #155 and #156 - I did make an effort to split up the most painful changes into chunks that are easy to review, and will hopefully make cherry-picking the useful features from this request much simpler after that.

**Comment by steamboatid** [comment]
> This doesn't look like a merge request prepared for merge into the official repository - the README.md is actually getting updated with the text `steamboatid's fork of apt-mirror`.
> 
> Please consider reviewing #154 #155 and #156 - I did make an effort to split up the most painful changes into chunks that are easy to review, and will hopefully make cherry-picking the useful features from this request much simpler after that.

the readme is changed due to "no maintener notif" in the main repo. It simply self intro to any changes I've made.
**Anyone is welcome to change the readme file as needed.**

**Comment by steamboatid** [comment]
> Not working anymore for some reason Using prepackaged mirror.list, but it's always says that "0 bytes will be downloaded into archive" with dry run I'm using debian buster in docker container, but in host ubuntu I have the same issue premirror.sh is from your repo Here's my log:
> 
> ```
> Running the Pre Mirror script ...                                                                                           
> (/UbuntuMirror/New/var/premirror.sh)                                                                                         
>                                                                                                                              
>                                                                                                                              
>  Pre Mirror script has completed. See above output for any possible errors.                                                  
>                                                                                                                              
>                                                                                                                              
>                                                                                                                              
>  Prepare indexes files: []                                                                                                   
>    Downloading 335 index files using 2 threads...                                                                            
> cat: /UbuntuMirror/New/var/index-log.0: No such file or directory                                                            
> =cat: /UbuntuMirror/New/var/index-log.1: No such file or directory                                                           
> =  current 404 Fails: 0                                                                                                      
>                                                                                                                              
>     Checksum Checking: Packages* files.. 
>    Preparing Packages* files checksum: [] {0 lines}. 
>    [Packages* Files] Checksum Type:    MD5      --- checksum file NOT exists
>    [Packages* Files] Checksum Type:   SHA1      --- checksum file NOT exists
>    [Packages* Files] Checksum Type: SHA256      --- checksum file NOT exists
> 
> 
>  Processing translation indexes: [TTTTT]
> 
>  Processing DEP-11 indexes: [DDDDD]
> 
>  Processing SHA256 by-hash files [HHHHH]
> 
>  Processing cnf indexes: [CCCCC]
> 
>  Processing debian-installer: [EEEEE]
> 
>  Processing debian-iso files: [IIIIII]
> 
>  Processing indexes: {S=source, B=Binary} [SS  BBBBB]
> 
>  No file with mismatch size found. 
> 
> 
>  Checksum Checking: Pre-Mirroring 
>    [Pre Mirroring] Checksum Type:    MD5        --- checksum file NOT exists
>    [Pre Mirroring] Checksum Type:   SHA1        --- checksum file NOT exists
>    [Pre Mirroring] Checksum Type: SHA256        --- checksum file NOT exists
> 
> 
> 
>  Main download.. 
> 
>  0 bytes will be downloaded into archive [0 urls].
>  A dry-run was requested, no download performed, exiting.
> ```

the dry-run option is there just to check all of the algo. NO files downloaded, so you may not see any download activities, not even the index files, with dry-run option enabled.

**Comment by SupaHiro** [comment]
I am going to close this pull request in favor of smaller more concise requests going forward. As requested I have begun reviewing 154-156.

> > This doesn't look like a merge request prepared for merge into the official repository - the README.md is actually getting updated with the text `steamboatid's fork of apt-mirror`.
> > Please consider reviewing #154 #155 and #156 - I did make an effort to split up the most painful changes into chunks that are easy to review, and will hopefully make cherry-picking the useful features from this request much simpler after that.
> 
> the readme is changed due to "no maintener notif" in the main repo. It simply self intro to any changes I've made. **Anyone is welcome to change the readme file as needed.**

**Pull request closed without merging**
