### PR TITLE
Update apt-mirror

### PR DESCRIPTION
**Pull request by sfinexer**
Correct start

### CODE REVIEW

**Comment by bdrung** [comment]
Can you please update the commit message to add an explanation for this proposed change?

**Comment by sfinexer** [comment]
It isn't sure yet that correctly.
But in the current situation, downloading of the file at murder of apt-mirror doesn't occur. apt-mirror passes it.

**Comment by sfinexer** [comment]
Option 1:
  exec 'wget', '--no-cache', '--limit-rate=' . get_variable("limit_rate"), '-t', '5', '-r', 'N', '-c', '-l', 'inf', '-o', get_variable("var_path") . "/$stage-log.$i", '-i', get_variable("var_path") . "/$stage-urls.$i", @args;
Option 2:
exec 'wget', '--no-cache', '--limit-rate=' . get_variable("limit_rate"), '-t', '5', '-r', '-nc', '-l', 'inf', '-o', get_variable("var_path") . "/$stage-log.$i", '-i', get_variable("var_path") . "/$stage-urls.$i", @args;

**Comment by bdrung** [comment]
The problem and explanation for your change is still unclear to me.

**Comment by sfinexer** [comment]
Old code
        if ( $pid == 0 )
        {
            exec 'wget', '--no-cache', '--limit-rate=' . get_variable("limit_rate"), '-t', '5', '-r', '-N', '-l', 'inf', '-o', get_variable("var_path") . "/$stage-log.$i", '-i', get_variable("var_path") . "/$stage-urls.$i", @args;
            # shouldn't reach this unless exec fails
            die("\n\nCould not run wget, please make sure its installed and in your path\n\n");
        }
Doesn't make additional charge of the begun files, it is necessary:
        if ( $pid == 0 )
        {
      #  exec 'wget', '--no-cache', '--limit-rate=' . get_variable("limit_rate"), '-t', '5', '-r', '-N', '-l', 'inf', '-o', get_variable("var_path") . "/$stage-log.$i", '-i', get_variable("var_path") . "/$stage-urls.$i", @args;
         if ( $stage eq 'archive')
           {
             exec 'wget', '--no-cache', '--limit-rate=' . get_variable("limit_rate"), '-t', '5', '-r', '-c', '-l', 'inf', '-o', get_variable("var_path") . "/$stage-log.$i", '-i', get_variable("var_path") . "/$stage-urls.$i", @args;
           }
        else
          {
             exec 'wget', '--no-cache', '--limit-rate=' . get_variable("limit_rate"), '-t', '5', '-r', '-N', '-l', 'inf', '-o', get_variable("var_path") . "/$stage-log.$i", '-i', get_variable("var_path") . "/$stage-urls.$i", @args;
          }
            # shouldn't reach this unless exec fails
            die("\n\nCould not run wget, please make sure its installed and in your path\n\n");
        }

**Comment by chutzimir** [comment]
I think this is trying to add `-c` to downloading the package files. I'd argue this is not a good idea - better restart the downloads from scratch.

What do you think @jbouse @SupaHiro , should just reject this?

**Pull request closed without merging**
