### PR TITLE
Adding support for 'deb [arch=amd64] ...' format

### LINKED ISSUE #32: Cannot handle 'deb [arch=amd64] http://...' format
When I try to create a mirror of [cloudera-cdh5](https://www.cloudera.com/content/cloudera-content/cloudera-docs/CDH5/latest/CDH5-Installation-Guide/cdh5ig_cdh5_install.html?scroll=topic_4_4_1_unique_1__section_dfx_p51_nj_unique_1), I found this error.

The apt list file is under `/etc/apt/sources.list.d/cloudera-cdh5.list` on my system, and the content is :

```
deb [arch=amd64] http://archive.cloudera.com/cdh5/ubuntu/precise/amd64/cdh precise-cdh5 contrib
deb-src http://archive.cloudera.com/cdh5/ubuntu/precise/amd64/cdh precise-cdh5 contrib
```

I try to do the mirror by following command and got errors:

``` bash
vagrant@ubuntu:~$ sudo apt-mirror /etc/apt/sources.list.d/cloudera-cdh5.list 
Downloading 15 index files using 15 threads...
Begin time: Mon Apr 14 17:04:35 2014
[15]... [14]... [13]... [12]... [11]... [10]... [9]... [8]... [7]... [6]... [5]... [4]... [3]... [2]... [1]... [0]... 
End time: Mon Apr 14 17:04:36 2014

Proceed indexes: [SPsh: 1: cannot open [arch=amd64]//dists/http://archive.cloudera.com/cdh5/ubuntu/precise/amd64/cdh/precise-cdh5/binary-amd64/Packages.gz: No such file
apt-mirror: can't open index in proceed_index_gz at /usr/bin/apt-mirror line 460.
vagrant@ubuntu:~$ 
```

If I have to change the apt .list to the form below to make it work:

```
deb-amd64 http://archive.cloudera.com/cdh5/ubuntu/precise/amd64/cdh precise-cdh5 contrib
deb-src http://archive.cloudera.com/cdh5/ubuntu/precise/amd64/cdh precise-cdh5 contrib
```
- OS: Ubuntu 12.04
- apt-mirror: 0.4.8-5

Could you add support of `[arch=amd64]`-like format? Thanks.

### PR DESCRIPTION
**Pull request by twang2218**
Fixes #32 

Signed-off-by: Tao Wang <twang2218@gmail.com>

### CODE REVIEW

**Comment by twang2218** [comment]
ping @bdrung

**Comment by bdrung** [comment]
This commit does not support lines containing spaces. Image these config lines:
```
deb [arch=i386] http://example.com stable main
deb [ arch=amd64 ] http://example.com stable main
deb [arch=i386 ] http://example.com stable main
```
They are all valid for apt-get.

**Comment by twang2218** [comment]
Good point. That's because the parser currently using split by `\s` to parse the line:

```python
    my @config_line = split;
    my $config_line = shift @config_line;
```

so if there are some spaces in the between, they will mess up the parser's logic.

Maybe we should parse the whole line in regular expression.

**Comment by twang2218** [comment]
@bdrung I reimplemented the parser to use regular expression for the parsing. I think it will be more robust for those cases.

I don't know how to write Perl unit test for this project, so I did my own test, here sample `test.list` I used:

```bash
deb [arch=i386] http://example.com stable main
deb [ arch=amd64 lang=en ] http://example.com stable main
  deb   [arch=i386 ] http://example.com stable main
 deb  [arch=i386,amd64 ] http://example.com stable main
deb http://httpredir.debian.org/debian jessie-updates main
deb-src http://httpredir.debian.org/debian jessie-updates main
#deb http://httpredir.debian.org/debian jessie-updates main
  #  deb-src http://httpredir.debian.org/debian jessie-updates main
deb-src http://httpredir.debian.org/debian jessie-updates main

deb-powerpc http://example.com/debian stable main contrib non-free

set base_path         /var/spool/apt-mirror
set mirror_path       $base_path/mirror
set _tilde            0
# Use --unlink with wget (for use with hardlinked directories)
set unlink            1
set use_proxy         off
set http_proxy        127.0.0.1:3128
set proxy_user        user

deb http://archive.ubuntu.com/ubuntu precise main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu precise-security main restricted universe multiverse

#deb-src http://archive.ubuntu.com/ubuntu precise main restricted universe multiverse

clean http://archive.ubuntu.com/ubuntu
skip-clean http://archive.ubuntu.com/ubuntu/
```

And here is the parsed result:


```bash
$ perl parse-config.pl
<Line:1>: deb [arch=i386] http://example.com stable main
Parsed result => $VAR1 = {
          'components' => [
                            'stable',
                            'main'
                          ],
          'uri' => 'http://example.com',
          'arch' => 'i386',
          'type' => 'deb',
          'options' => 'arch=i386'
        };
<Line:2>: deb [ arch=amd64 lang=en ] http://example.com stable main
Parsed result => $VAR1 = {
          'options' => ' arch=amd64 lang=en ',
          'type' => 'deb',
          'uri' => 'http://example.com',
          'components' => [
                            'stable',
                            'main'
                          ],
          'arch' => 'amd64'
        };
<Line:3>:   deb   [arch=i386 ] http://example.com stable main
Parsed result => $VAR1 = {
          'components' => [
                            'stable',
                            'main'
                          ],
          'uri' => 'http://example.com',
          'arch' => 'i386',
          'type' => 'deb',
          'options' => 'arch=i386 '
        };
<Line:4>:  deb  [arch=i386,amd64 ] http://example.com stable main
Parsed result => $VAR1 = {
          'components' => [
                            'stable',
                            'main'
                          ],
          'uri' => 'http://example.com',
          'arch' => 'i386',
          'options' => 'arch=i386,amd64 ',
          'type' => 'deb'
        };
<Line:5>: deb http://httpredir.debian.org/debian jessie-updates main
Parsed result => $VAR1 = {
          'options' => undef,
          'type' => 'deb',
          'uri' => 'http://httpredir.debian.org/debian',
          'components' => [
                            'jessie-updates',
                            'main'
                          ],
          'arch' => undef
        };
<Line:6>: deb-src http://httpredir.debian.org/debian jessie-updates main
Parsed result => $VAR1 = {
          'options' => undef,
          'type' => 'deb-src',
          'uri' => 'http://httpredir.debian.org/debian',
          'components' => [
                            'jessie-updates',
                            'main'
                          ],
          'arch' => undef
        };
<Line:9>: deb-src http://httpredir.debian.org/debian jessie-updates main
Parsed result => $VAR1 = {
          'options' => undef,
          'type' => 'deb-src',
          'arch' => undef,
          'uri' => 'http://httpredir.debian.org/debian',
          'components' => [
                            'jessie-updates',
                            'main'
                          ]
        };
<Line:11>: deb-powerpc http://example.com/debian stable main contrib non-free
Parsed result => $VAR1 = {
          'type' => 'deb',
          'options' => undef,
          'arch' => 'powerpc',
          'components' => [
                            'stable',
                            'main',
                            'contrib',
                            'non-free'
                          ],
          'uri' => 'http://example.com/debian'
        };
<Line:13>: set base_path         /var/spool/apt-mirror
Parsed result => $VAR1 = {
          'type' => 'set',
          'value' => '/var/spool/apt-mirror',
          'key' => 'base_path'
        };
<Line:14>: set mirror_path       $base_path/mirror
Parsed result => $VAR1 = {
          'key' => 'mirror_path',
          'type' => 'set',
          'value' => '$base_path/mirror'
        };
<Line:15>: set _tilde            0
Parsed result => $VAR1 = {
          'value' => '0',
          'type' => 'set',
          'key' => '_tilde'
        };
<Line:17>: set unlink            1
Parsed result => $VAR1 = {
          'value' => '1',
          'type' => 'set',
          'key' => 'unlink'
        };
<Line:18>: set use_proxy         off
Parsed result => $VAR1 = {
          'key' => 'use_proxy',
          'type' => 'set',
          'value' => 'off'
        };
<Line:19>: set http_proxy        127.0.0.1:3128
Parsed result => $VAR1 = {
          'key' => 'http_proxy',
          'type' => 'set',
          'value' => '127.0.0.1:3128'
        };
<Line:20>: set proxy_user        user
Parsed result => $VAR1 = {
          'value' => 'user',
          'type' => 'set',
          'key' => 'proxy_user'
        };
<Line:22>: deb http://archive.ubuntu.com/ubuntu precise main restricted universe multiverse
Parsed result => $VAR1 = {
          'arch' => undef,
          'components' => [
                            'precise',
                            'main',
                            'restricted',
                            'universe',
                            'multiverse'
                          ],
          'uri' => 'http://archive.ubuntu.com/ubuntu',
          'type' => 'deb',
          'options' => undef
        };
<Line:23>: deb http://archive.ubuntu.com/ubuntu precise-security main restricted universe multiverse
Parsed result => $VAR1 = {
          'type' => 'deb',
          'options' => undef,
          'arch' => undef,
          'uri' => 'http://archive.ubuntu.com/ubuntu',
          'components' => [
                            'precise-security',
                            'main',
                            'restricted',
                            'universe',
                            'multiverse'
                          ]
        };
<Line:27>: clean http://archive.ubuntu.com/ubuntu
Parsed result => $VAR1 = {
          'uri' => 'http://archive.ubuntu.com/ubuntu',
          'type' => 'clean'
        };
<Line:28>: skip-clean http://archive.ubuntu.com/ubuntu/
Parsed result => $VAR1 = {
          'type' => 'skip-clean',
          'uri' => 'http://archive.ubuntu.com/ubuntu/'
        };
<%config_variables> => $VAR1 = {
          'unlink' => '1',
          'mirror_path' => '$base_path/mirror',
          'http_proxy' => '127.0.0.1:3128',
          'base_path' => '/var/spool/apt-mirror',
          '_tilde' => '0',
          'use_proxy' => 'off',
          'proxy_user' => 'user'
        };
<@config_binaries> => $VAR1 = [
          [
            'i386',
            'http://example.com',
            'stable',
            'main'
          ],
          [
            'amd64',
            'http://example.com',
            'stable',
            'main'
          ],
          [
            'i386',
            'http://example.com',
            'stable',
            'main'
          ],
          [
            'i386',
            'http://example.com',
            'stable',
            'main'
          ],
          [
            'amd64',
            'http://httpredir.debian.org/debian',
            'jessie-updates',
            'main'
          ],
          [
            'powerpc',
            'http://example.com/debian',
            'stable',
            'main',
            'contrib',
            'non-free'
          ],
          [
            'amd64',
            'http://archive.ubuntu.com/ubuntu',
            'precise',
            'main',
            'restricted',
            'universe',
            'multiverse'
          ],
          [
            'amd64',
            'http://archive.ubuntu.com/ubuntu',
            'precise-security',
            'main',
            'restricted',
            'universe',
            'multiverse'
          ]
        ];
<@config_sources> => $VAR1 = [
          [
            'http://httpredir.debian.org/debian',
            'jessie-updates',
            'main'
          ],
          [
            'http://httpredir.debian.org/debian',
            'jessie-updates',
            'main'
          ]
        ];
<%skipclean> => $VAR1 = {
          'archive.ubuntu.com/ubuntu' => 1
        };
<%clean_directory> => $VAR1 = {
          'archive.ubuntu.com/ubuntu' => 1
        };
```

**Comment by twang2218** [comment]
I just read the issue #43 and PR #51 . Should we allow space in the variable?

Currently, the `apt-mirror` cannot handle such case, but I can change the RegEx in the parser to handle them if they are single quoted or double quoted:

```diff
-    } elsif ( $line =~ /set[\t ]+(?<key>[^\s]+)[\t ]+(?<value>[^\s]+)/ ) {
+    } elsif ( $line =~ /set[\t ]+(?<key>[^\s]+)[\t ]+(?<value>"[^"]+"|'[^']+'|[^\s]+)/ ) {
        $config{'type'} = 'set';
        $config{'key'} = $+{key};
        $config{'value'} = $+{value};
```

@bdrung What do you think?

**Comment by twang2218** [comment]
ping @bdrung

**Comment by bdrung** [comment]
I merged your current commit. The proposed change for single or double quoted values look good. Another merge proposal will be welcome. :+1:

**Comment by twang2218** [comment]
@bdrung Done, create a PR #67 for the quoted value support.

**Pull request closed without merging**
