### PR TITLE
Certificate configuration does not depend on proxy

### PR DESCRIPTION
**Pull request by chutzimir**
The certificate configuration is currently inside an 'if use_proxy' block which was not intended.

### CODE REVIEW

**Review by SupaHiro — APPROVED** [review]
Nice , catch thank you!

**Comment by SupaHiro** [comment]
@chutzimir  do you think we should also add in the certificate-type parameter here?

**Comment by chutzimir** [comment]
> @chutzimir do you think we should also add in the certificate-type parameter here?

To be honest I am not much excited about adding all possible wget parameters to apt-mirror itself.

If I need to pass another-important-option to wget, I'd write a shell script called `wget` that calls `/usr/bin/wget --certificate-type=xxx --another-important-option "$@"`, put it in `/etc/apt` or something, and run apt-mirror with `env PATH=/etc/apt:$PATH apt-mirror /etc/apt/mirror.list` or similar.

**Comment by SupaHiro** [comment]
> > @chutzimir do you think we should also add in the certificate-type parameter here?
> 
> To be honest I am not much excited about adding all possible wget parameters to apt-mirror itself.
> 
> If I need to pass another-important-option to wget, I'd write a shell script called `wget` that calls `/usr/bin/wget --certificate-type=xxx --another-important-option "$@"`, put it in `/etc/apt` or something, and run apt-mirror with `env PATH=/etc/apt:$PATH apt-mirror /etc/apt/mirror.list` or similar.

Ok I'll go ahead and merge this and I'll make notes in the release that the cert option will only natively support pem certs. Thanks!

**Pull request merged**
