### PR TITLE
add support client certificate auth

### LINKED ISSUE #75: Support For SSL based repo's with keys
Would it be possible to support repos that use SSL keys to authenticate

nginx repo comes to mind.

### PR DESCRIPTION
**Pull request by ihard**
add support client certificate auth 
fix #75

### CODE REVIEW

**Comment by SupaHiro** [comment]
@ihard  I would like to add this to our next milestone. Can you rebase your PR?

**Comment by ihard** [comment]
@SupaHiro done

**Comment by chutzimir** [comment]
@ihard Can you review the changes after the rebase? Some unrelated things got added, please try to recreate your branch if necessary. I think it is meant to look like this: https://github.com/chutzimir/apt-mirror/commit/330f6d841565bf86aed2362a205ff1d1c0373c5f

**Comment by ihard** [comment]
@chutzimir  I recreate branch

**Review by SupaHiro — APPROVED** [review]
Looks good, thanks @ihard !

**Pull request merged**
