### PR TITLE
Contents-all

### PR DESCRIPTION
**Pull request by snumac**
Hello!

Possible and tested:
```
...
438:+            add_url_to_download( $url . "Contents-" . "all" . ".gz" );
...
447:+              add_url_to_download( $url . $_ . "/Contents-" . "all" . ".gz" );
...
```
TY

### CODE REVIEW

**Comment by snumac** [comment]
Good afternoon!
May i know which pull request in unfeasible? the one i suggested? i remind it was tested and fillfull our concern.
The fact is i pulled six commits since the  3a0de57 and i had to go back because the uncompressed files "release" where missing.
Thank you in advance! L.

**Comment by chutzimir** [comment]
@snumac if there is a specific patch you are suggesting, I am sure it is OK to raise a pull request that only has that one patch required. As is, this pull request was pulling a lot of changes.

**Comment by snumac** [comment]
Hello. Thank you for the answer.
I am not that sure those changes won't break my repository, neither they will fullfill my wish. 
I simply was willing to stay in the mainstream while achieving taking into account the "Contents-all.gz" files which are visible since Bullseye for Debian.
Were those changes you applied requested before mine?... The one i requested might have been not formaly correct but one could have done to me a recall on how to formaly do a patch request correctly.
I did read and applied all the changes that were made to the code up to the sixth commit since 95352eb but that did not work, some other repositories were broken: some "release" files were missing and i could not understand the logic of the evolution.
It's up to me now to test the pull until now but i need time.
Thank you for your comprehension.

**Comment by snumac** [comment]
Goot morning!
After pulling again since hash 97352eb, this time 20 commits, it seems at first sight apt-mirror (2838aa70cd5c06499e8e8e5d97fb51e41f445fa29b78a68f484713e7ee636bfa) is working correctly. 
TY for the help.
L.

**Pull request closed without merging**
