### PR TITLE
Add support for quoted variable with spaces

### LINKED ISSUE #43: Spaces in file paths?
I can't figure out how to specify a path with spaces in it (in mirror.list).
Enclosing in double quotes -> the double quotes are literally a part of the path.
Backslash before space -> the backslash becomes a part of the path.

### PR DESCRIPTION
**Pull request by twang2218**
Fixes #43 
Signed-off-by: Tao Wang <twang2218@gmail.com>

### CODE REVIEW

**Comment by bdrung** [comment]
Spaces in the base_pash does not work. Example:
```
set base_path    "/tmp/apt-mirror/space ' test"
set postmirror_script $var_path/clean.sh
set nthreads     2

deb [ arch= amd64] http://ppa.launchpad.net/mozillateam/xul-ext/ubuntu zesty main
```
Calling the post mirror script will fail.

**Comment by twang2218** [comment]
Fixed the `postmirror_script` issue.

* Added new function `quoted_path` to quote and escape the path.
* Added support of space in options such as `[ arch= amd64]`;
* replace `mkdir` and `mkpath` to `make_path`;
* Change the `system()` call to `system COMMAND LIST` to handle the spaces in path or argument cases.

**Comment by bdrung** [comment]
I used ```[ arch= amd64]```in the test case, but that format is not accepted by apt:
```
E: Malformed entry 1 in list file /etc/apt/sources.list ([option] not assignment)
```
My bad. So support of space in options is not needed. I will merge your commit without that change.

Thanks you very much! Are you interesting in co-maintaining apt-mirror?

**Comment by twang2218** [comment]
oh, I thought I missed the `[ arch= amd64]` case. 😸 

I'm currently working on several other projects, I don't have any time for this project currently, and I'm not good at Perl anyway, it took me quite some time to understand the code and fix the issues. So I'm sorry that I cannot take this offer, but thanks for the offer anyway. 😃

**Pull request closed without merging**
